---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bluedeployment
  labels:
    app: bluedeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bluedeployment
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 60
  progressDeadlineSeconds: 600
  template:
    metadata:
      labels:
        app: bluedeployment
    spec:
      containers:
      - name: capstone
        image: 01123555566/capstone
        ports:
        - containerPort: 80
          

---
apiVersion: v1
kind: Service
metadata:
  name: greendeploymenttt
spec:
  type: LoadBalancer
  selector:
    app: bluedeployment
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80